baseURL = "/"
languageCode = "en"
title = "Digital Tea House"
theme = "maintaince"
paginate = 6



[params]

description = "Digital Tea House : ကျုပ်တို့  ရဲ့ လက်ဘက်ရည်ဆိုင် 'Digital Tea House'  က ပုံမှန်လက်ဘက်ရည်ဆိုင်မဟုတ်ဘူးဗျ။ ဒစ်ဂျစ်တယ်လက်ဘက်ရည်ဆိုင် ။"




mobile = "+95 (9) 453336775"
email = "contact@digitalteahouse.info"
address = "Innwa Residence, Innwa street, South Oakkalar Pa Tsp , Yangon,Myanmar"
contact_form_action = "#"


